version: '3.7'

services:

  baget:
    image: loicsharma/baget:latest
    environment:
      ApiKey: ${NuGetServerApiKey:-8e7b324ee43b689f77c2f95b099fd6f5}
      Storage__Type: FileSystem
      Storage__Path: /var/baget
      Database__Type: Sqlite
      Database__ConnectionString: Data Source=/var/baget/baget.db
      Search__Type: Database
    ports:
    - 30080:80/tcp
    volumes:
    - baget-data:/var/baget:rw

  pihole:
    image: pihole/pihole:latest
    dns:
    - 127.0.0.1
    - 9.9.9.9
    - 9.9.9.10
    environment:
      DNS1: 9.9.9.9
      DNS2: 9.9.9.10
      TZ: UTC
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD:-76c9eca2bced3e751a47c188afe6fd9d}
    ports:
    - 40053:53/tcp
    - 40053:53/udp
    - 40067:67/udp
    - 40080:80/tcp
    - 40443:443/tcp
    restart: unless-stopped
    volumes:
    - pihole-volume-dnsmasq:/etc/dnsmasq.d/:rw
    - pihole-volume-pihole:/etc/pihole/:rw

volumes:
  baget-data: {}
  pihole-volume-dnsmasq: {}
  pihole-volume-pihole: {}
