version: '3.7'

services:

  yarp:
    image: eassbhhtgu/yarpspike:latest
    environment:
      ReverseProxy:Routes:route1:ClusterId: "cluster1"
      ReverseProxy:Routes:route1:Match:Hosts:0: "nuget"
      ReverseProxy:Routes:route2:ClusterId: "cluster2"
      ReverseProxy:Routes:route2:Match:Hosts:0: "pihole"
      ReverseProxy:Clusters:cluster1:Destinations:destination1:Address: "http://nuget/"
      ReverseProxy:Clusters:cluster2:Destinations:destination1:Address: "http://pihole/"
    ports:
    - 80:80/tcp

  nuget:
    image: loicsharma/baget:latest
    environment:
      ApiKey: ${NuGetServerApiKey:-8e7b324ee43b689f77c2f95b099fd6f5}
      Storage__Type: FileSystem
      Storage__Path: /var/baget
      Database__Type: Sqlite
      Database__ConnectionString: Data Source=/var/baget/baget.db
      Search__Type: Database
    volumes:
    - baget-data:/var/baget:rw

  pihole:
    image: pihole/pihole:latest
    dns:
    - 127.0.0.1
    - 9.9.9.9
    - 9.9.9.10
    environment:
      DNS1: 9.9.9.9
      DNS2: 9.9.9.10
      TZ: UTC
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD:-76c9eca2bced3e751a47c188afe6fd9d}
    restart: unless-stopped
    volumes:
    - pihole-volume-dnsmasq:/etc/dnsmasq.d/:rw
    - pihole-volume-pihole:/etc/pihole/:rw

volumes:
  baget-data: {}
  pihole-volume-dnsmasq: {}
  pihole-volume-pihole: {}
