version: '3.7'

services:

  yarp:
    image: eassbhhtgu/yarp:latest
    environment:
      ReverseProxy:Routes:route1:ClusterId: cluster1
      ReverseProxy:Routes:route1:Match:Hosts:0: nuget
      ReverseProxy:Routes:route2:ClusterId: cluster2
      ReverseProxy:Routes:route2:Match:Hosts:0: pi.hole
      ReverseProxy:Clusters:cluster1:Destinations:destination1:Address: http://gateway.docker.internal:30080/
      ReverseProxy:Clusters:cluster2:Destinations:destination1:Address: http://gateway.docker.internal:40080/
    networks:
      default: null
    ports:
    - 80:80/tcp

networks:
  default:
    name: yarp_default
