version: '3.7'

services:

  yarp:
    image: eassbhhtgu/yarpspike:latest
    environment:
      ReverseProxy:Routes:route1:ClusterId: "cluster1"
      ReverseProxy:Routes:route1:Match:Hosts:0: "nuget"
      ReverseProxy:Routes:route2:ClusterId: "cluster2"
      ReverseProxy:Routes:route2:Match:Hosts:0: "pihole"
      ReverseProxy:Clusters:cluster1:Destinations:destination1:Address: "http://nuget/"
      ReverseProxy:Clusters:cluster2:Destinations:destination1:Address: "http://pihole/"
    ports:
    - 80:80/tcp

